
export default new Map([
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/playground.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fplayground.mdx&astroContentModuleFlag=true")],
["src/content/docs/concepts/step.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fconcepts%2Fstep.mdx&astroContentModuleFlag=true")],
["src/content/docs/concepts/results.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fconcepts%2Fresults.mdx&astroContentModuleFlag=true")],
["src/content/docs/concepts/workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fconcepts%2Fworkflows.mdx&astroContentModuleFlag=true")],
["src/content/docs/comparison/awaitly-vs-effect.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomparison%2Fawaitly-vs-effect.mdx&astroContentModuleFlag=true")],
["src/content/docs/comparison/awaitly-vs-neverthrow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomparison%2Fawaitly-vs-neverthrow.mdx&astroContentModuleFlag=true")],
["src/content/docs/comparison/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomparison%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/docs/comparison/awaitly-vs-try-catch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fcomparison%2Fawaitly-vs-try-catch.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/claude-skill.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fclaude-skill.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/framework-integration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fframework-integration.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/migration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fmigration.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/eslint-plugin.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Feslint-plugin.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/static-analysis.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fstatic-analysis.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/retries-timeouts.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Fretries-timeouts.mdx&astroContentModuleFlag=true")],
["src/content/docs/guides/troubleshooting.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fguides%2Ftroubleshooting.mdx&astroContentModuleFlag=true")]]);
		